notice(fresh) + addModal
Amfiteatr42/React-Node-TeamProject pull request #8
Opened 2023-01-31 10:42 UTC by EugeneDemchenko

2023-01-31 21:58 UTC, Amfiteatr42 requested changes

2023-01-31 21:58 UTC, Amfiteatr42 commented on src/redux/notices/notice-operation.js
> +      await axios.post(`/api/userspets/add`, values, header);
неправильный эндпоинт
тебе сюда - /api/ads/add

2023-01-31 21:58 UTC, Amfiteatr42 commented on src/redux/notices/notice-operation.js
> +      const { data } = await axios.get(`/api/userspets/add`, header);
правильный эндпоинт - /api/ads/my

2023-01-31 21:58 UTC, Amfiteatr42 commented on src/pages/NoticesPage/NoticesPage.jsx
> +  }, []);
не пойму что за юзэффект? что делает первый иф?
п.с. Вова сделает по умолчанию так, что будет открываться /notices/sell

2023-01-31 21:58 UTC, Amfiteatr42 commented on src/components/App.jsx
> +            <Route path="own" element={<NoticesCategoriesList />} />
вернуть на родину "/notices/:categoryName" )

2023-01-31 21:58 UTC, Amfiteatr42 commented on src/redux/store.js
> +const persistedNoticesReducer = persistReducer(persistConfig, noticesReducer);
нам вроде не нужно в локалсторедж сохранять нотисы, пусть в стейте просто висят?

2023-02-01 12:14 UTC, EugeneDemchenko commented on src/redux/store.js
> +const persistedNoticesReducer = persistReducer(persistConfig, noticesReducer);
без этого селекторы мои не видит

2023-02-01 12:42 UTC, EugeneDemchenko commented on src/redux/notices/notice-operation.js
> +      await axios.post(`/api/userspets/add`, values, header);
+

2023-02-01 12:42 UTC, EugeneDemchenko commented on src/redux/notices/notice-operation.js
> +      const { data } = await axios.get(`/api/userspets/add`, header);
+

2023-02-02 19:58 UTC, merged